feat: TE7-T1022:  Implement custom drawer UI
jigar-s-simform/ts-assignment pull request #25
Opened 2023-07-14 09:58 UTC by jigar-s-simform

Implement custom UI for drawer

2023-07-14 10:28 UTC, amitkajwani-simformsolutions approved these changes

2023-07-14 10:28 UTC, amitkajwani-simformsolutions commented on android/app/build.gradle
Why did this gradle file change in this PR as it is not related to drawer UI?

2023-07-14 10:28 UTC, amitkajwani-simformsolutions commented on app/components/custom-drawer/CustomDrawer.tsx
> +                Strings.emptyString +
Instead of Strings.emptyString you can use backticks ``

2023-07-14 10:32 UTC, jigar-s-simform commented on android/app/build.gradle
because made release apk from this branch yesterday as it was the latest code and was working fine without any bugs!

2023-07-14 11:21 UTC, amitkajwani-simformsolutions commented on android/app/build.gradle
That is fine but this should not belong to this PR. Raise a separate PR for that and remove it from this PR.

2023-07-18 06:46 UTC, amitkajwani-simformsolutions requested changes

2023-07-18 06:46 UTC, amitkajwani-simformsolutions commented on android/app/build.gradle
This change should not be in this PR, and I don't think there is any change in this so you can revert it.
And before raising the PR make sure to review it properly.

2023-07-18 06:49 UTC, jigar-s-simform commented on android/app/build.gradle
there is a change as you mentioned earlier I removed the changes in build.gradle as it was not related to this pr so it is not showing in the changed files !! that was the change

2023-07-18 09:53 UTC, sagar-simformsolutions approved these changes

2023-07-18 10:02 UTC, amitkajwani-simformsolutions approved these changes

2023-07-18 10:02 UTC, merged