feat: TE7-T1022: Implement theme change for home screen using mmkv
jigar-s-simform/ts-assignment pull request #46
Opened 2023-07-26 14:31 UTC by jigar-s-simform

Implement theme change for home screen using mmkv for settings, videos and notifications screens

2023-07-26 16:06 UTC, sagar-simformsolutions requested changes

2023-07-26 16:06 UTC, sagar-simformsolutions commented on app/modules/notifications/NotificationsEmptyComponent.tsx
> +  const { theme } = useNotification();
add types

2023-07-26 16:06 UTC, sagar-simformsolutions commented on app/modules/notifications/useNotification.ts
> +  const [mmkvTheme] = useMMKVString(
add types

2023-07-26 16:06 UTC, sagar-simformsolutions commented on app/modules/settings/BottomSheetButton.tsx
> +  const [mmkvTheme] = useMMKVString(StorageConstants.themeStorageKey, mmkvStorage);
add types

2023-07-26 16:06 UTC, sagar-simformsolutions commented on app/modules/settings/WebViewComponent.tsx
> +  const [mmkvTheme] = useMMKVString(
add types

2023-07-26 16:06 UTC, sagar-simformsolutions commented on app/modules/settings/useSettings.ts
> +  const [mmkvTheme, setMmkvTheme] = useMMKVString(
add types

2023-07-27 05:49 UTC, jigar-s-simform commented on app/modules/notifications/NotificationsEmptyComponent.tsx
> +  const { theme } = useNotification();
resolved

2023-07-27 05:49 UTC, jigar-s-simform commented on app/modules/notifications/useNotification.ts
> +  const [mmkvTheme] = useMMKVString(
resolved

2023-07-27 05:49 UTC, jigar-s-simform commented on app/modules/settings/BottomSheetButton.tsx
> +  const [mmkvTheme] = useMMKVString(StorageConstants.themeStorageKey, mmkvStorage);
resolved

2023-07-27 05:49 UTC, jigar-s-simform commented on app/modules/settings/WebViewComponent.tsx
> +  const [mmkvTheme] = useMMKVString(
resolved

2023-07-27 05:49 UTC, jigar-s-simform commented on app/modules/settings/useSettings.ts
> +  const [mmkvTheme, setMmkvTheme] = useMMKVString(
resolved

2023-07-27 05:51 UTC, sagar-simformsolutions approved these changes

2023-07-27 05:51 UTC, merged