feat: TE7-T1022: Implement Navigation setup
jigar-s-simform/ts-assignment pull request #7
Opened 2023-07-11 14:42 UTC by jigar-s-simform

Implement navigation setup for rest of the screens

2023-07-11 14:54 UTC, sagar-simformsolutions requested changes

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
why are we providing ref as 2 in this. ?

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/modules/videos/VideosListScreen.tsx
> +const VideosListScreen = () => (
add types in this

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/modules/create-user/CreateUserScreen.tsx
> +const CreateUserScreen = () => <Text>{Strings.bottomNavigationTitles.create}</Text>;
add return type

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/modules/details/DetailsScreen.tsx
> +const DetailsScreen = () => (
add types

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/navigation/HomeStack.tsx
> +const HomeStack = () => {
add types

2023-07-11 14:54 UTC, sagar-simformsolutions commented on app/navigation/HomeTabs.tsx
> +const HomeTabs = () => {
add types

2023-07-11 14:58 UTC, jigar-s-simform commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
It is a custom hook that returns an array of ref objects that are applied to form input fields to achieve the functionality of jumping on to next form field by clicking on next return key type. Here in the login form we have two fields therefore we need to initialize array of two refs which this hook will return

2023-07-11 15:03 UTC, jigar-s-simform commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
resolved

2023-07-11 15:03 UTC, jigar-s-simform commented on app/modules/videos/VideosListScreen.tsx
> +const VideosListScreen = () => (
resolved

2023-07-11 15:04 UTC, jigar-s-simform commented on app/modules/create-user/CreateUserScreen.tsx
> +const CreateUserScreen = () => <Text>{Strings.bottomNavigationTitles.create}</Text>;
resolved

2023-07-11 15:04 UTC, jigar-s-simform commented on app/modules/details/DetailsScreen.tsx
> +const DetailsScreen = () => (
resolved

2023-07-11 15:04 UTC, jigar-s-simform commented on app/navigation/HomeStack.tsx
> +const HomeStack = () => {
resolved

2023-07-11 15:04 UTC, jigar-s-simform commented on app/navigation/HomeTabs.tsx
> +const HomeTabs = () => {
resolved

2023-07-11 15:14 UTC, sagar-simformsolutions commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
@jigar-s-simform 
this is not a correct way to jump on next button, please check properly

2023-07-11 15:36 UTC, jigar-s-simform commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
it is just giving number of refs needed in current form so that we don't have to write useRef individually for every input field

2023-07-12 06:22 UTC, sagar-simformsolutions requested changes

2023-07-12 06:22 UTC, sagar-simformsolutions commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
@jigar-s-simform 
If this is working, then make sure you put optional chaining in  all the execution of the code which relates to this including in "useSubmitEdit" function aswell

2023-07-12 06:53 UTC, jigar-s-simform commented on app/modules/login/useLogin.ts
> +  const formRefs = useInitializationRef(2);
resolved

2023-07-12 06:56 UTC, sagar-simformsolutions approved these changes

2023-07-12 07:02 UTC, merged